#!/bin/sh
#############
. ./variables
#############
mkdir -pm 700 "${functions}" "${keyring}" "${builds}" "${downloads}" "${packages}" "${rootfs}" "${work}"
#############
printf "%s\n" "${work}" > .gitignore
printf "%s\n" "${rootfs}" > .gitignore
#############
chown "${USER}:" "${functions}" "${keyring}" "${builds}" "${downloads}" "${packages}" "${rootfs}" "${work}"
chmod -R 700     "${functions}" "${keyring}" "${builds}" "${downloads}" "${packages}" "${rootfs}" "${work}"
#############
printf "11\nS\nQ\n1\n0\n${name:-${USER}}\n${email:-${USER}@$(cat /proc/sys/kernel/hostname)}\n${comment}\nO\n"|
gpg --no-tty --expert --full-generate-key --allow-freeform-uid --command-fd /dev/stdin --pinentry-mode loopback --passphrase ''
#############
printf "addkey\n12\n1\n1y\naddkey\n10\n1\n1y\nsave\n"|
gpg --no-tty --expert --command-fd /dev/stdin --pinentry-mode loopback --passphrase '' --edit-key "${USER}"
#############
curl https://ftp.gnu.org/gnu/gnu-keyring.gpg|gpg --import
curl https://www.musl-libc.org/musl.pub|gpg --import
#############
