#!/bin/sh
############# value=0 on press
press=0
state=0
# blinky lights mount and flash && reboot || static light
(while :;do sleep 1;read</sys/class/gpio/gpio3/value
 if [[ "${REPLY}" == "0" ]];then
  if [[ "${press}" == "0" ]];then press=1
   (while :;do for i in 0 13;do printf "%s\n" "${i}" > /sys/class/leds/gl-ar300m\:green\:lan/brightness;sleep .3;done;done) &
   mount -o rw,nodev,nosuid,noexec,noatime /dev/sda /storage
   mtd -re firmware write /storage/gl-ar300m firmware
   umount /storage
   printf "%s\n" "13" > /sys/class/leds/gl-ar300m\:green\:wlan/brightness
   sleep 2
   kill %%
   printf "%s\n" "0" > /sys/class/leds/gl-ar300m\:green\:wlan/brightness
   printf "%s\n" "0" > /sys/class/leds/gl-ar300m\:green\:lan/brightness
  fi
 else press="0";fi
done & ) &>/dev/null &
#############
