#!/bin/sh
#############
scale(){
   if [ "${#1}" -lt "4"  ];then tmp="${1}b"
 elif [ "${#1}" -lt "7"  ];then tmp="$((${1}/1000))k"
 elif [ "${#1}" -lt "10" ];then tmp="$((${1}/1000000))m"
 else                           tmp="$((${1}/1000000000))g";fi
 printf "%s\n" "${tmp:0:9}"
}
 left(){ tmp="${1}";until [ "${#tmp}" -ge "${2}" ];do tmp="${tmp} ";done;printf "%s\n" "${tmp:0:${2}}"; }
right(){ tmp="${1}";until [ "${#tmp}" -ge "${2}" ];do tmp=" ${tmp}";done;printf "%s\n" "${tmp:0:${2}}"; }
#############

#############
while :;do clear
#############
printf "%s\n" "##############################################"
#############
[ -z "${network1}" ] && network0="$(awk 'NR>2{printf$1$2":"$10" "}' /proc/net/dev)" || network0="${network1}"
                        network1="$(awk 'NR>2{printf$1$2":"$10" "}' /proc/net/dev)"
#############
count=1
until [ "${count}" -gt "$(printf "%s\n" "${network0}"|wc -w)" ];do
IFS=":" read interface0 receive0 transmit0 << EOF
$(printf "%s\n" "${network0}"|cut -d ' ' -f "${count}")
EOF
IFS=":" read interface1 receive1 transmit1 << EOF
$(printf "%s\n" "${network1}"|cut -d ' ' -f "${count}")
EOF
       interface="$(left ${interface0} 8)"
 current_receive="$(right $(scale $((${receive1}-${receive0}))) 6)"
current_transmit="$(right $(scale $((${transmit1}-${transmit0}))) 6)"
   total_receive="$(right $(scale ${receive1}) 6)"
  total_transmit="$(right $(scale ${transmit1}) 6)"
printf "%s\n" "${interface} [v${current_receive} ^${current_transmit}] [v${total_receive} ^${total_transmit}]"
count="$((${count}+1))"
done
#############
printf "%s\n" "##############################################"
#############
[ -z "${disk1}" ] && disk0="$(awk '{printf$3":"$6":"$10" "}' /proc/diskstats)" || disk0="${disk1}"
                     disk1="$(awk '{printf$3":"$6":"$10" "}' /proc/diskstats)"
#############
count=1
until [ "${count}" -gt "$(printf "%s\n" "${disk0}"|wc -w)" ];do
IFS=":" read device0 read0 write0 << EOF
$(printf "%s\n" "${disk0}"|cut -d ' ' -f "${count}")
EOF
IFS=":" read device1 read1 write1 << EOF
$(printf "%s\n" "${disk1}"|cut -d ' ' -f "${count}")
EOF
       device="$(left ${device0} 8)"
current_write="$(right $(scale $(((${write1}-${write0})*512))) 6)"
 current_read="$(right $(scale $(((${read1}-${read0})*512))) 6)"
  total_write="$(right $(scale $((${write1}*512))) 6)"
   total_read="$(right $(scale $((${read1}*512))) 6)"
printf "%s\n" "${device} [v${current_write} ^${current_read}] [v${total_write} ^${total_read}]"
count="$((${count}+1))"
done
#############
printf "%s\n" "##############################################"
#############
sleep "${1:-1}"
done
#############
