#!/usr/bin/sh
#############
. /etc/services/variables httpd
#############
[ -f "${service_storage}/error" ] || install -o 0 -g 80 -m 0640 "${service_system}/error" "${service_storage}/error"
[ -f "${service_storage}/config" ] || install -o 0 -g 80 -m 0640 "${service_system}/config" "${service_storage}/config"
#############
[ -d "${service_storage}/webroot" ] || install -d -o 0 -g 80 -m 0750 "${service_storage}/webroot"
[ -d "${service_storage}/webroot/css" ] || install -o 0 -g 0 -m 0640 "${service_system}/css" "${service_storage}/webroot/css"
[ -f "${service_storage}/webroot/index" ] || install -o 0 -g 80 -m 0640 "${service_system}/index" "${service_storage}/webroot/index"
#############
[ -d "${service_storage}/webroot/cgi-bin" ] || install -d -o 0 -g 80 -m 0750 "${service_storage}/webroot/cgi-bin"
[ -f "${service_storage}/webroot/cgi-bin/project.cgi" ] || install -o 0 -g 0 -m 0640 "${service_system}/project.cgi" "${service_storage}/webroot/cgi-bin/project.cgi"
[ -f "${service_storage}/webroot/cgi-bin/project.git" ] || install -o 0 -g 0 -m 0640 "${service_system}/project.git" "${service_storage}/webroot/cgi-bin/project.git"
#############
[ -L "${service_storage}/webroot/shared" ] || ln -sf "${shared}" "${service_storage}/webroot/shared"
#############
[ -d "${service_storage}/repo" ] || install -d -o 0 -g 0 -m 0750 "${service_storage}/repo"
#############
[ -d "${service_storage}/repo/project" ] || git init --bare --initial-branch project "${service_storage}/repo/project"
#############
. /etc/services/permissions 0 80 0750 0640
#############
chown -R httpd:httpd "${service_storage}/repo"
#############
