#!/bin/sh
#############
. /etc/services/variables httpd
#############

[ -d "${service_storage}/webroot" ] || install -d -o 0 -g 80 -m 0640 "${service_storage}/webroot"

[ -f "${service_storage}/config" ] || install -o 0 -g 80 -m 0640 "${service_system}/files/config" "${service_storage}/config"

[ -f "${service_storage}/error" ] || install -o 0 -g 80 -m 0640 "${service_system}/files/error" "${service_storage}/error"

#############

[ -d "${service_storage}/webroot/cgi-bin" ] || install -d -o 0 -g 80 -m 0640 "${service_storage}/webroot/cgi-bin"

[ -f "${service_storage}/webroot/index" ] || install -o 0 -g 80 -m 0640 "${service_system}/files/index" "${service_storage}/webroot/index"

[ -L "${service_storage}/webroot/shared" ] || ln -sf "${shared}" "${service_storage}/webroot/shared"

#############
# [ -f "${service_storage}/webroot/cgi-bin/project.cgi" ] || printf "%s\n\n" "Content-type: text/html" > "${service_storage}/webroot/cgi-bin/project.cgi"
# [ -f "${service_storage}/webroot/cgi-bin/project.git" ] || printf "%s\n" "GIT_PROJECT_ROOT=/run/git GIT_HTTP_EXPORT_ALL= exec /usr/libexec/git-core/git-http-backend" > "${service_storage}/webroot/cgi-bin/project.git"
#############
. /etc/services/permissions root httpd 0750 0640
#############
