#!/bin/sh
#############
. /etc/services/httpd/install
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/ash -c "exec env -i /sbin/httpd -p 80 -h '${service_storage}/webroot' -c '${service_storage}/config' </dev/null &>/dev/null & exit" httpd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +10 -u "httpd"
#############
