#!/bin/sh
#############
debug(){ printf "%s\n" "debug - ${1}" ; exit 1 ; }
#############
[ "${#}" == "1" ] || [ "${#}" == "2" ] || debug "takes interface &| hostname"
#############
[ -d "/sys/class/net/${1}" ] || debug "interface does not exist"
#############
[ -z "${2}" ] || hostname="-xhostname:${2}"
#############
pkill udhcpc
#############
ip link set up "${1}"
#############
env -i /sbin/udhcpc -vSnqfa2000 -i "${1}" -s /bin/udhcpc_ping ${hostname}
#############
