#!/bin/sh
#############
[ "${1}" == "bound" ] || return 1
#############
[ -z "${interface}" ] || [ -z "${ip}" ] || [ -z "${subnet}" ] || [ -z "${router}" ] && return 1
#############
cat << EOF
#############
# interface:${interface}
#############
#    domain:${hostname}.${domain}
#   gateway:${router}
# broadcast:${broadcast}
#     lease:${ip}/${mask} ${lease}
#############
#      dnsd:${dns}
#    ntpsrv:${ntpsrv}
#############
EOF
#############
read -rp 'continue ?'
#############

[ -z "${broadcast}" ] && broadcast="" || broadcast="broadcast ${broadcast}"

ip link set down dev "${interface}"
ip addr flush dev "${interface}"

ip addr add "${ip}/${subnet}" ${broadcast} dev "${interface}"
ip link set up "${interface}"

ip route del default
ip route add default via "${router}" dev "${interface}" scope global metric 0

#############
[ -z "${opt96}" ] || ip addr add "${opt96}::${ip//./:}/64" dev "${interface}"
[ -z "${opt96}" ] || ip -6 route del default
[ -z "${opt96}" ] || ip -6 route add default via "${opt96}::${router//./:}" dev "${interface}" scope global metric 0
#############

#############
[ -L "/etc/resolv.conf" ] || ln -sf /run/resolv.conf /etc/resolv.conf
#############
[ -z "${dns}" ] || install -o 0 -g 0 -m 0664 /dev/null /run/resolv.conf
[ -z "${dns}" ] || for i in ${dns} ; do printf "%s\n" "nameserver ${i}" >> /run/resolv.conf ; done
#############

#############

 install -d -o 0 -g 0 -m 0700 "/run/udhcpc" "/run/udhcpc/${interface}"

 printf "%s\n" "${broadcast##* }" > "/run/udhcpc/${interface}/broadcast"
           printf "%s\n" "${dns}" > "/run/udhcpc/${interface}/dns"
        printf "%s\n" "${domain}" > "/run/udhcpc/${interface}/domain"
        printf "%s\n" "${router}" > "/run/udhcpc/${interface}/gateway"
      printf "%s\n" "${hostname}" > "/run/udhcpc/${interface}/hostname"
            printf "%s\n" "${ip}" > "/run/udhcpc/${interface}/ip"
         printf "%s\n" "${lease}" > "/run/udhcpc/${interface}/lease"
          printf "%s\n" "${mask}" > "/run/udhcpc/${interface}/mask"
        printf "%s\n" "${ntpsrv}" > "/run/udhcpc/${interface}/ntpsrv"

 find /run/udhcpc -type d -exec chmod 0755 {} \;
 find /run/udhcpc -type f -exec chmod 0644 {} \;

#############

