#!/bin/sh
#############
# broken busybox syslogd added .000 milliseconds to all date timestamps
#############
## [uptime]---[oldest_log]-----[newest_log]-[epoch]
## epoch-uptime  == total length of time the system has been up
## newest-oldest == length of time recorded logs cover
## oldest-uptime == how long the systems been up since the last recorded log entry
#############
## percentage of covered logs in relation to total uptime
## percentage of missing logs in relation to total uptime
#############
cd /run/logs || exit 1
#############

 [ -s syslog   ] && oldest="$(date --date="$(awk 'NR==1{print$1" "$2" "$3" 2024"}' syslog  )" +%s)"
 [ -s syslog.0 ] && oldest="$(date --date="$(awk 'NR==1{print$1" "$2" "$3" 2024"}' syslog.0)" +%s)"
 [ -s syslog.1 ] && oldest="$(date --date="$(awk 'NR==1{print$1" "$2" "$3" 2024"}' syslog.1)" +%s)"
 [ -s syslog.2 ] && oldest="$(date --date="$(awk 'NR==1{print$1" "$2" "$3" 2024"}' syslog.2)" +%s)"
                    newest="$(date --date="$(awk 'END  {print$1" "$2" "$3" 2024"}' syslog  )" +%s)"

#############
uptime="$(date --date="$(uptime -s)" +%s)"
epoch="$(date +%s)"
#############
missing=$((((${oldest}-${uptime})*100)/(${epoch}-${uptime})))
covered=$((((${newest}-${oldest})*100)/(${epoch}-${uptime})))
#############
printf "%s\n" "# covered:${covered}% # missing:${missing}%"
#############

