#!/bin/sh
#############

while sleep 7 ; do

 [ "${counter:-0}" == "0" ] && counter="1" && printf "%s\n" "nameserver 127.0.0.1" > /run/resolv.conf && continue
#[ "${counter:-0}" == "0" ] && counter="1" && printf "%s\n" "this" && continue

 [ "${counter:-0}" == "1" ] && counter="0" && printf "%s\n" "nameserver 172.16.0.1" > /run/resolv.conf && continue
#[ "${counter:-0}" == "1" ] && counter="0" && printf "%s\n" "that" && continue

done

#############
