#!/bin/sh
#############
# i.setup
# ^ minimum loop to connect and printf everything
# i.input <arg0>
# ^ while loop to raw server || privmsg <arg0>
# i.bot <arg0>
# ^ while loop to raw server || privmsg <arg0> && eval ${message}
#############

 install -d -o "${USER}" -m 0700 "${HOME}/ircd" && cd "${HOME}/ircd" || exit 1 ; clear

   [ -f "DEBUG" ] || install -o "${USER}" -m 0600 "/dev/null" "DEBUG"
   [ -f "ERROR" ] || install -o "${USER}" -m 0600 "/dev/null" "ERROR"
    [ -f "META" ] || install -o "${USER}" -m 0600 "/dev/null" "META"
  [ -f "NOTICE" ] || install -o "${USER}" -m 0600 "/dev/null" "NOTICE"
 [ -f "PRIVMSG" ] || install -o "${USER}" -m 0600 "/dev/null" "PRIVMSG"
    [ -f "SELF" ] || install -o "${USER}" -m 0600 "/dev/null" "SELF"
    [ -f "SENT" ] || install -o "${USER}" -m 0600 "/dev/null" "SENT"
  [ -f "filter" ] || install -o "${USER}" -m 0600 "/dev/null" "filter"

#############
nick="NICK $(tr -cd 'a-zA-Z'</dev/urandom|head -c13)"
user="USER $(tr -cd 'a-zA-Z'</dev/urandom|head -c9) 0 0 :$(tr -cd 'a-zA-Z'</dev/urandom|head -c47)~"
#############
red="\e[31m" green="\e[32m" yellow="\e[33m" blue="\e[34m"
purple="\e[35m" cyan="\e[36m" white="\e[37m" grey="\e[38m"
#############
reset="\e[0m"

#############

  [ -f "sasl"  ] || exit 1
 [ -f ".ping"  ] && rm ".ping"
  [ -e "input" ] && rm "input"
  [ -e "input" ] || mkfifo -m 0600 "input"
  [ -e "input" ] && exec 3<>input

#############

while sleep 60
do
 touch .ping
 printf "${cyan}%s${reset}\n" '#'
 printf "%s\n" "PING :irc.libera.chat" >&3
 sleep 13 && [ -f .ping ] && pkill -P$$
done &

#############

printf "%s\n%s\n%s\n%s\n%s\n%s\n" "cap REQ sasl" "${nick}" "${user}" "AUTHENTICATE EXTERNAL" "AUTHENTICATE +" "CAP END" >&3 &

#############

openssl s_client -noservername -connect irc.libera.chat:6697 -cert "sasl" -tls1_3 -verify 1 -verify_return_error -verify_quiet -quiet <&3 |
tr -cd '[:alnum:]:.!@/#\n ' |
while read -r sender type target message ; do

 color="${green}" output="DEBUG"
 [ "${type}" == "PRIVMSG" ] && color="${red}" output="PRIVMSG"
 [ "${type}" == "NOTICE" ] && color="${yellow}" output="NOTICE"

 [ "${sender}" == "PING" ] && color="${cyan}" output="META"
 [ "${sender}" == "PING" ] && printf "%s\n" "PONG ${type}" >&3

 [ "${type}" == "PONG" ] && color="${cyan}" output="META"
 [ "${type}" == "PONG" ] && [ -f .ping ] && rm .ping

 [ "${type}" == "NICK" ] ; then color="${grey}" output="META"
 [ "${type}" == "MODE" ] ; then color="${grey}" output="META"
 [ "${type}" == "JOIN" ] ; then color="${grey}" output="META"
 [ "${type}" == "PART" ] ; then color="${grey}" output="META"
 [ "${type}" == "QUIT" ] ; then color="${grey}" output="META"
 [ "${type}" == "KICK" ] ; then color="${grey}" output="META"
 [ "${type}" == "TOPIC" ] ; then color="${grey}" output="META"
 [ "${type}" == "INVITE" ] ; then color="${grey}" output="META"
 [ "${type}" == "WALLOPS" ] ; then color="${yellow}" output="NOTICE"

 [ "${sender}" == "ERROR" ] ; then printf "%s\n" "[${account}] [${nick}] [${user}] [${sender} ${type} ${target} ${message}]" >> ERROR ; pkill -P$$
 [   "${type}" == "432"   ] ; then printf "%s\n" "[${account}] [${nick}] [${user}] [${sender} ${type} ${target} ${message}]" >> ERROR ; pkill -P$$
 [   "${type}" == "433"   ] ; then printf "%s\n" "[${account}] [${nick}] [${user}] [${sender} ${type} ${target} ${message}]" >> ERROR ; pkill -P$$
 [   "${type}" == "461"   ] ; then printf "%s\n" "[${account}] [${nick}] [${user}] [${sender} ${type} ${target} ${message}]" >> ERROR ; pkill -P$$
 [   "${type}" == "904"   ] ; then printf "%s\n" "[${account}] [${nick}] [${user}] [${sender} ${type} ${target} ${message}]" >> ERROR ; pkill -P$$
 [   "${type}" == "001"   ] ; then printf "%s\n" "${regain}"   >&3 ; sleep 13
                                        printf "%s\n" "${mode}"     >&3 ; sleep 3
                                        printf "%s\n" "${channels}" >&3 ; printf "\n"

 printf "${color}%s${reset}" "#"

 rainbow_sender="\e[38;5;$((16#$(printf "%s\n" "${sender}"|md5sum|head -c2)))m"
 rainbow_target="\e[38;5;$((16#$(printf "%s\n" "${target}"|md5sum|head -c2)))m"
 trim="${sender:0:23}" ; until [ "${#trim}" -ge "23" ] ; do trim=" ${trim}" ; done

 printf "${rainbow_sender}%s${red}%s${rainbow_target}%s${highlight}%s${reset}\n" "[${trim}]" "[${type}]" "[${target}]" "[${message}]" >> "${output}"

done &

#############
wait
#############

