#!/bin/sh
#############
. /etc/services/variables maild
#############

#############
. /etc/services/permissions maild maild 0700 0600
#############

#############
install -d -o 2525 -g 0    -m 0700 "${service_storage}/incoming"
install -d -o 0    -g 2525 -m 0770 "${service_storage}/offline"
install -d -o 2525 -g 0    -m 0700 "${service_storage}/purge"
install -d -o 2525 -g 0    -m 0700 "${service_storage}/queue"
install -d -o 2525 -g 0    -m 0700 "${service_storage}/temporary"
#############
[ -f "${service_storage}/smtpd.conf" ] || install -o 25 -g 25 -m 0600 "${service_system}/smtpd.conf" "${service_storage}"
#############
[ -f "${service_storage}/vdomains" ] || echo onion > "${service_storage}/vdomains"
[ -f "${service_storage}/vuserbase" ] || install -o 25 -g 25 -m 0600 "${service_system}/vuserbase" "${service_storage}"
[ -f "${service_storage}/vusers" ] || {
 printf "%s\n" "root@onion public" > "${service_storage}/vusers"
 printf "%s\n" "$(tr -cd 'a-z'</dev/urandom|head -c6)@onion private" >> "${service_storage}/vusers"
 printf "%s\n" "$(tr -cd 'a-z'</dev/urandom|head -c6)@onion private" >> "${service_storage}/vusers"
 printf "%s\n" "$(tr -cd 'a-z'</dev/urandom|head -c6)@onion private" >> "${service_storage}/vusers"
 printf "%s\n" "@onion junk" >> "${service_storage}/vusers"
}
chown maild:maild "${service_storage}/vdomains" "${service_storage}/vuserbase" "${service_storage}/vusers"
chmod 0644 "${service_storage}/vdomains" "${service_storage}/vuserbase" "${service_storage}/vusers"
#############
install -d -o 0 -g 0 -m 0711 "${service_storage}"
#############

