#!/bin/sh
#############
. /etc/services/variables gitd
#############
[ -f "${service_storage}/error" ] || install -o gitd -g gitd -m 0600 "${service_system}/error" "${service_storage}/error"
[ -f "${service_storage}/config" ] || install -o gitd -g gitd -m 0600 "${service_system}/config" "${service_storage}/config"
#############
[ -d "${service_storage}/webroot" ] || install -d -o gitd -g gitd -m 0700 "${service_storage}/webroot"
[ -f "${service_storage}/webroot/css" ] || install -o gitd -g gitd -m 0600 "${service_system}/css" "${service_storage}/webroot/css"
[ -f "${service_storage}/webroot/index" ] || install -o gitd -g gitd -m 0600 "${service_system}/index" "${service_storage}/webroot/index"
#############
[ -d "${service_storage}/webroot/cgi-bin" ] || install -d -o gitd -g gitd -m 0700 "${service_storage}/webroot/cgi-bin"
[ -f "${service_storage}/webroot/cgi-bin/project.cgi" ] || install -o gitd -g gitd -m 0600 "${service_system}/project.cgi" "${service_storage}/webroot/cgi-bin/project.cgi"
[ -f "${service_storage}/webroot/cgi-bin/project.git" ] || install -o gitd -g gitd -m 0600 "${service_system}/project.git" "${service_storage}/webroot/cgi-bin/project.git"
#############
[ -d "${service_storage}/repo" ] || install -d -o gitd -g gitd -m 0700 "${service_storage}/repo"
#############
[ -d "${service_storage}/repo/project" ] || git init --bare --initial-branch project "/tmp/storage/services/gitd/repo/project"
#############
. /etc/services/permissions gitd gitd 0700 0600
#############

