#!/bin/sh
#############
. /etc/services/gitd/install
#############
# pgrep -x /sbin/httpd &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/ash -c "setsid env -i /sbin/httpd -p 9418 -h '${service_storage}/webroot' -c '${service_storage}/config' </dev/null &>/dev/null & exit" gitd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +10 -u "gitd"
#############
