#!/bin/sh
#############
umask 077

############# cleanup

rm -r /etc/config
rm -r /etc/hotplug.d
rm -r /etc/init.d
rm -r /etc/modules-boot.d
rm -r /etc/modules.d
rm -r /etc/rc.d
rm -r /etc/sysctl.d
rm -r /etc/unbound

rm -r /lib/wifi
rm -r /lib/netifd

rm -r /usr/bin

rm -r /usr/lib/opkg
rm -r /usr/lib/unbound

rm -r /usr/sbin/unbound-checkconf

rm -r /var

############# ulimit
ulimit -f 14680064  # file size (blocks)
ulimit -t unlimited # cpu time (seconds)
ulimit -d unlimited # data seg size (kb)
ulimit -s 8192      # stack size (kb)
ulimit -c 0         # core file size (blocks)
ulimit -m unlimited # resident set size (kb)
ulimit -l 64        # locked memory (kb)
ulimit -p 23        # processes
ulimit -n 1024      # file descriptors
ulimit -v unlimited # address space (kb)
ulimit -w unlimited # locks
ulimit -e 0         # scheduling priority
ulimit -r 0         # real-time priority

############# filesystem
mount -t proc -o rw,nodev,nosuid,noexec,noatime,hidepid=2 proc /proc
mount -o remount,hidepid=2 /proc
mount -t sysfs -o rw,nodev,nosuid,noexec,noatime sysfs /sys
mount -t devtmpfs -o rw,dev,nosuid,noexec,noatime,size=0 devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts -o ro,dev,nosuid,noexec,noatime,mode=0600 devpts /dev/pts
mount -t tmpfs -o rw,nodev,nosuid,noexec,noatime,size=7% tmpfs /tmp
#############
mount -o remount,ro,nosuid,noatime,size="$(df|awk 'NR==2{print$3}')k" /

############# # modules - hahahahahahahahahahahaha seriously tho
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done

############# logs
syslogd -SDC1000
klogd

############# # sysctl
sysctl -p /etc/sysctl.conf

############# # network

echo 'openwrt' > /proc/sys/kernel/hostname
echo 'localdomain' > /proc/sys/kernel/domainname

nft -f /etc/nftables.rules

ip addr add 127.0.0.1/8 dev lo brd + scope host
ip route add 127.0.0.0/8 dev lo scope host
ip link set up lo

ip link set up eth0
ip addr add 192.168.0.197/24 dev eth0

ip link set up eth1
ip addr add 192.168.3.1/24 dev eth1
ip addr add fd03::1/64 dev eth1

ip link set up wlan0
ip addr add 192.168.1.1/24 dev wlan0
ip addr add fd01::1/64 dev wlan0

hostapd -B /etc/hostapd

ip route add default via 192.168.0.1

############# # services
touch /tmp/leases.lan /tmp/leases.man
chown 67:67 /tmp/leases.lan /tmp/leases.man
chmod 600 /tmp/leases.lan /tmp/leases.man
touch /tmp/root-anchors
chown 53:53 /tmp/root-anchors
chmod 600 /tmp/root-anchors
#############
ntpd -q -p 87.81.181.2 -p 93.93.129.102 -p 129.250.35.251 -p 87.124.126.49
#############
telnetd -b 192.168.3.1:23 -f /etc/banner -l /sbin/ffs
#############
su -s /bin/sh -c "unbound-anchor -a /tmp/root-anchors" unbound
unbound -c /etc/unbound.conf
udhcpd -S /etc/udhcpd-lan
udhcpd -S /etc/udhcpd-man
radvd -C /etc/radvd.conf -u udhcpd -p /tmp/radvd.pid
ntpd -l

############# # gpio
printf "%s\n" "3" > /sys/class/gpio/export
buttons

