#!/bin/sh
#############
script -c 'emerge                     -avuDN --onlydeps @z.wayland' /tmp/desktop.host
script -c 'emerge --root /run/desktop -avuDN --nodeps @z.wayland' /tmp/desktop.rootfs
#############
cp -a /lib64/libmount.* /run/desktop/lib64
cp -a /lib64/libblkid.* /run/desktop/lib64
#############
cp -a /usr/lib/locale/locale-archive /run/desktop/usr/lib/locale
#############
install -o root -g root -m 0755 /etc/self/e.sets/sets_startw /run/desktop/usr/bin/startw
#############

