#!/bin/sh
#############

 emerge --root /run/desktop -avbkuDN --nodeps @desktop
 emerge --root /run/firefox -avbkuDN --nodeps @.firefox

 cp -a /run/firefox/* /run/desktop

for i in /usr/lib/gcc/x86_64-pc-linux-gnu/*
do
 cp -a ${i}/libstdc* /run/desktop/lib64
 cp -a ${i}/libgcc_s* /run/desktop/lib64
done

 cp -a /lib64/libuuid.so* /run/desktop/lib64 # desktop
 cp -a /lib64/libblkid.* /run/desktop/lib64 # firefox dep
 cp -a /lib64/libmount.* /run/desktop/lib64 # firefox dep

 install -o root -g root -m 0755 /etc/self/e.sets/sets_startx /run/desktop/usr/bin/startx

 install -o root -g root -m 0755 /etc/self/e.sets/sets_xinitrc /run/desktop/etc/xinitrc

#############

