#!/bin/sh
#############
usage(){ printf "%s\n" "${1}" ; exit 1 ; }
#############
[ -f "binhost/kernels/virtual" ] || usage "binhost/kernels/virtual does not exist"
#############
[ -f "binhost/images/client" ] || usage "binhost/images/client does not exist"
#############

  defaults="-nodefaults -daemonize -runas qemu -chroot /var/empty -sandbox on -k en-gb -L /usr/share/qemu"
       cpu="-cpu host -smp 4,sockets=1,cores=4 -enable-kvm" mem="-m 8G" gpu="-vga virtio"
   network="-netdev tap,id=nd0,script=/etc/qemu-nat,downscript=no"
 interface="-device virtio-net-pci,netdev=nd0,mac=52:54:00:00:00:00"
    kernel="-kernel /tmp/storage/stage3/binhost/kernels/virtual"
    initrd="-initrd /tmp/storage/stage3/binhost/images/client"
       vnc="-nographic -display none -vnc unix:/dev/shm/qemu"

 qemu-system-x86_64 ${defaults} ${cpu} ${mem} ${gpu} ${network} ${interface} ${kernel} ${initrd} ${vnc}

#############

 until [ -e /dev/shm/qemu ] ; do sleep .1 ; done

  chown 1:1 /dev/shm/qemu

 chmod 0600 /dev/shm/qemu

 printf "%s\n" "nc -lks local:/dev/shm/qemu -e dbclient user@172.16.0.1 nc local:/dev/shm/qemu"

#############

