#############
EAPI="7"
#############
DESCRIPTION="libowfat"
HOMEPAGE=""
SRC_URI="https://www.fefe.de/libowfat/${P}.tar.xz"
#############
LICENSE=""
SLOT="0"
KEYWORDS="amd64"
IUSE=""
RDEPEND=""
DEPEND="${RDEPEND}"
#############
