#!/usr/bin/sh -l
#############
umask 0007
#############
print(){

 printf "%s\n" "#############"
 printf "%s\n" "# ${1}"
 printf "%s\n" "#############"

}
#############
print system.mount ; . /etc/scripts/b.init/system.mount
print system.tmp   ; . /etc/scripts/b.init/system.tmp  2>&1 | tee /dev/shm/log.tmp
print system.dev   ; . /etc/scripts/b.init/system.dev  2>&1 | tee /dev/shm/log.dev
print system.proc  ; . /etc/scripts/b.init/system.proc 2>&1 | tee /dev/shm/log.proc
print system.sys   ; . /etc/scripts/b.init/system.sys  2>&1 | tee /dev/shm/log.sys
#############
print system.log  ; . /etc/scripts/b.init/system.log  2>&1 | tee /dev/shm/log.log
print system.lock ; . /etc/scripts/b.init/system.lock 2>&1 | tee /dev/shm/log.lock
#############
print sysctl ; sysctl -p /etc/sysctl.conf &>/dev/null
#############
print storage.fde ; grep -q -e desktop /proc/cmdline && /usr/bin/sh -l # timeout -s SIGTERM 3 sh -c 'read -p interupt && /usr/bin/sh -l'
#############
[ "$(hostname)" == "server" ] && mdadm -q --manage --stop /dev/md126
[ "$(hostname)" == "server" ] && mdadm -q --manage --stop /dev/md127
[ "$(hostname)" == "server" ] && mdadm -q --assemble --no-degraded --scan
[ "$(hostname)" == "server" ] && ln -sf "$(findfs LABEL=bootfs 2>/dev/null || echo /dev/null)" /dev/bootfs
[ "$(hostname)" == "server" ] && ln -sf "$(findfs LABEL=storage 2>/dev/null || echo /dev/null)" /dev/storage
[ "$(hostname)" == "server" ] && ln -sf "$(findfs LABEL=shared 2>/dev/null || echo /dev/null)" /dev/shared
#############
print storage.mount  ; . /etc/scripts/b.init/storage.mount  2>&1 | tee /dev/shm/log.mount
print storage.setup  ; . /etc/scripts/b.init/storage.setup  2>&1 | tee /dev/shm/log.setup
print storage.shared ; . /etc/scripts/b.init/storage.shared 2>&1 | tee /dev/shm/log.shared
#############
print system.network ; . /etc/scripts/b.init/system.network 2>&1 | tee /dev/shm/log.network
#############
[ "$(hostname)" == "server" ] && . /etc/scripts/z.testing/b.server start
[ "$(hostname)" == "server" ] && . /etc/scripts/z.testing/b.client start
#############
[ "$(hostname)" == "virtual" ] && { brctl delif lan eth0 ; brctl addif nat eth0 ; }
[ "$(hostname)" == "virtual" ] && { echo yes | ash /etc/scripts/e.setpriv/setpriv_network_dhcpc nat ; }
[ "$(hostname)" == "virtual" ] && { echo yes | ash /etc/scripts/e.setpriv/setpriv_network_zcip nat ; }
[ "$(hostname)" == "virtual" ] && { . /etc/scripts/z.testing/b.client start ; }
#############
[ -f "${storage}/.init" ] && . "${storage}/.init" ; clear
#############

