#!/usr/bin/sh
#############
defaults="-nodefaults -daemonize -runas qemu -run-with chroot=/var/empty -sandbox on -k en-gb -L /usr/share/qemu"
#############
cpu="-cpu host -smp 2,sockets=1,cores=2 -enable-kvm" mem="-m 4G" gpu="-vga virtio"
#############
network="-netdev tap,id=nd0,script=/etc/qemu-lan,downscript=no"
network="-netdev tap,id=nd0,script=/etc/qemu-nat,downscript=no"
#############
interface="-device virtio-net-pci,netdev=nd0,mac=52:54:00:XX:XX:XX"
#############
kernel="-kernel XXX -append root=/dev/vda"
initrd="-initrd XXX"
boot="-drive if=virtio,index=0,format=raw,media=cdrom,file=XXX"
file="-drive if=virtio,index=1,format=raw,media=disk,file=XXX"
extra="-drive if=virtio,index=2,format=raw,media=disk,file=XXX"
#############
vnc="-nographic -display none -vnc unix:/dev/shm/qemu"
#############

#############
qemu-system-x86_64 ${defaults} ${cpu} ${mem} ${gpu} ${network} ${interface} ${kernel} ${initrd} ${boot} ${file} ${extra} ${vnc} ${usb}
#############
chown user:user /dev/shm/qemu
#############
#usb="-usb -device qemu-xhci usb-host,vendorid=0x1234,productid=0x1234"
#############

