#!/bin/sh
#############

for i in $(seq 30 39);do

 printf " "
 printf "\033[${i}m"
 printf "${i}:testing"
 printf "\033[0m"
 printf " "
 printf "\033[01;${i}m"
 printf "${i}:testing"
 printf "\033[0m\n"
 printf " "

 sleep .1

done

#############

