#!/bin/sh
#############
[ "${#}" == "0" ] && nft -nnn list set netdev interfaces blacklist4
#############
[ "${#}" == "1" ] && nft add element netdev interfaces blacklist4 { "${1}" timeout 1h }
#############
[ "${#}" == "2" ] && nft add element netdev interfaces blacklist4 { "${1}" timeout "${2}" }
#############
