#!/bin/sh
#############
printf "%s\n" "24" >> /sys/class/gpio/export
#############
flash_led(){
 while :;do
  for i in 0 1;do
   printf "%s\n" "${i}" >> /sys/class/leds/shelby\:white\:power/brightness
   sleep 1
  done
 done
}
#############
(while :;do sleep 1

 read</sys/class/gpio/gpio24/value

 [ "${REPLY}" == "0" ] && {

  if [ -f /tmp/.lock ];then
   pkill telnetd
   kill %%
   printf "%s\n" "1" >> /sys/class/leds/shelby\:white\:power/brightness
   rm /tmp/.lock
  else
   telnetd -l /sbin/ffs -f /etc/banner -b 192.168.1.1:23
   flash_led &
   touch /tmp/.lock
  fi

 }

done &) </dev/null &>/dev/null &
#############

