#!/bin/sh
#############
. ../bin/variables

#############
usage(){ printf "\n${0} - ${1}\n-i input\n-r root\n-p persistent\n-t tmp\n-h help\n\n";exit; }

#############
while getopts "i:rpth" arg;do
 case "${arg}" in
  i) input="${OPTARG}";;
  r) key="root.pem";;
  p) key="persistent.pem";;
  t) key="tmp.pem";;
  h) usage "sign input";;
  *) usage "sign input";;
 esac
done

#############
[[ -z "${key}" ]] && usage "requires a signing key"
[[ -f "${input}" ]] || usage "input does not exist"
[[ -f "${input}.dgst" ]] && usage "input.dgst already exists"

#############
openssl dgst -sha512 -sign "${key}" -out "${input}.dgst" "${input}"

