#!/bin/sh
#############
[ "$(stat -c %i /)" == "1" ] && exit 1
#############
cd /root/repos || exit 1
#############

for i in \
browser \
communication \
emulation \
overlay \
overflow \
testing \
xorg ; do

printf "\n%s\n" "[${i}]"

find "${i}" -name '*.ebuild' -exec basename {} \; | while read ; do

grep "${REPLY::-7}" /binhost/logs/build.onlydeps /binhost/logs/build.nodeps /binhost/logs/chroot.world |
grep -q \
-e ::browser \
-e ::communication \
-e ::emulation \
-e ::overflow \
-e ::overlay \
-e ::testing \
-e ::xorg &&
 printf "%s\e[32m%s\e[0m\n\n" "${REPLY::-7}: " "pass" ||
  printf "%s\e[31m%s\e[0m\n\n" "${REPLY::-7}: " "fail" 

done | sort -u

done | /usr/bin/less -R

#############

