#!/bin/sh
#############
. /etc/services/variables
#############
export readonly vpnd_system="${services_system}/vpnd"
export readonly vpnd_storage="${services_storage}/vpnd"
export readonly vpnd_tmp="${services_tmp}/vpnd"
#############
for i in "${vpnd_storage}" "${vpnd_tmp}";do
install -d -o vpnd -g vpnd -m 2770 "${i}"
chown -R vpnd:vpnd "${i}"
find "${i}" -type d -exec chmod 2770 {} \;
find "${i}" -type f -exec chmod 0660 {} \;
done
#############
