#!/bin/sh
#############
printf "%s\n" "#############"
printf "%s\n" "# [executing /sbin/init]"
printf "%s\n" "#############"
#############
sleep 3
#############
exec /sbin/init # </dev/null &>/dev/null
#############
