#!/usr/bin/sh
#############
printf "%s\n" "#############"
printf "%s\n" "# [executing /usr/sbin/init]"
printf "%s\n" "#############"
#############
rm /init ; rmdir /root ; sleep 3
#############
exec /usr/sbin/init
#############
