#!/bin/sh
#############
press=0
state=0
(while :;do sleep 1;read</sys/class/gpio/gpio11/value
 if [[ "${REPLY}" == "1" ]];then
  if [[ "${press}" == "0" ]];then press=1
   if [[ "${state}" == "0" ]];then
    mount -o rw,nodev,nosuid,noexec,noatime /dev/sda /storage || continue
    httpd -c /etc/httpd -u httpd:httpd -h /storage/httpd -p 192.168.1.1:80 || { umount /storage;continue; }
    printf "%s\n" "13" > /sys/class/leds/tp-link\:green\:3g/brightness
    printf "%s\n" "13" > /sys/class/leds/tp-link\:green\:wlan/brightness
    printf "%s\n" "13" > /sys/class/leds/tp-link\:green\:lan/brightness
    printf "%s\n" "13" > /sys/class/leds/tp-link\:green\:wps/brightness
    state=1
   elif [[ "${state}" == "1" ]];then
    pkill httpd
    umount /storage
    pgrep httpd && continue
    mountpoint -q /storage && continue
    printf "%s\n" "0" > /sys/class/leds/tp-link\:green\:3g/brightness
    printf "%s\n" "0" > /sys/class/leds/tp-link\:green\:wlan/brightness
    printf "%s\n" "0" > /sys/class/leds/tp-link\:green\:lan/brightness
    printf "%s\n" "0" > /sys/class/leds/tp-link\:green\:wps/brightness
    state=0
   fi
  fi
 elif [[ "${REPLY}" == "0" ]];then
  [[ "${press}" == "1" ]] && press="0"
 fi
done & ) &>/dev/null &
#############
