#!/bin/sh
#############
. /etc/services/ircd/install
#############
pgrep -x ngircd &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/sh -c "setsid ngircd --config ${service_storage}/ngircd.conf </dev/null &>/dev/null & exit" ircd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +10 -u "ircd"
#############
