
#ifndef DROPBEAR_DEFAULT_OPTIONS_H_
#define DROPBEAR_DEFAULT_OPTIONS_H_

#define DROPBEAR_DEFPORT "22"
#define DROPBEAR_DEFADDRESS ""

#define DSS_PRIV_FILENAME "/dev/null"
#define RSA_PRIV_FILENAME "/dev/null"
#define ECDSA_PRIV_FILENAME "/dev/null"
#define ED25519_PRIV_FILENAME "~/.ssh/sshd"

#define NON_INETD_MODE 1
#define INETD_MODE 0

#define DROPBEAR_REEXEC 1

#define DEBUG_TRACE 0
#define DROPBEAR_SMALL_CODE 0

#define DROPBEAR_X11FWD 0
#define DROPBEAR_CLI_LOCALTCPFWD 1
#define DROPBEAR_CLI_REMOTETCPFWD 1
#define DROPBEAR_SVR_LOCALTCPFWD 1
#define DROPBEAR_SVR_REMOTETCPFWD 1
#define DROPBEAR_SVR_AGENTFWD 0
#define DROPBEAR_CLI_AGENTFWD 0

#define DROPBEAR_CLI_PROXYCMD 0
#define DROPBEAR_CLI_NETCAT 0

#define DROPBEAR_USER_ALGO_LIST 0

#define DROPBEAR_AES128 0
#define DROPBEAR_AES256 0
#define DROPBEAR_3DES 0
#define DROPBEAR_CHACHA20POLY1305 1

#define DROPBEAR_ENABLE_CTR_MODE 0
#define DROPBEAR_ENABLE_CBC_MODE 0
#define DROPBEAR_ENABLE_GCM_MODE 0

#define DROPBEAR_SHA1_HMAC 0
#define DROPBEAR_SHA2_256_HMAC 0
#define DROPBEAR_SHA2_512_HMAC 0
#define DROPBEAR_SHA1_96_HMAC 0

#define DROPBEAR_RSA 0
#define DROPBEAR_RSA_SHA1 0
#define DROPBEAR_DSS 0
#define DROPBEAR_ECDSA 0
#define DROPBEAR_ED25519 1
#define DROPBEAR_SK_KEYS 0
#define DROPBEAR_DEFAULT_RSA_SIZE 4096

#define DROPBEAR_DELAY_HOSTKEY 0

#define DROPBEAR_DH_GROUP14_SHA1 0
#define DROPBEAR_DH_GROUP14_SHA256 0
#define DROPBEAR_DH_GROUP16 0
#define DROPBEAR_CURVE25519 1
#define DROPBEAR_ECDH 0
#define DROPBEAR_DH_GROUP1 0
#define DROPBEAR_DH_GROUP1_CLIENTONLY 1

#define DROPBEAR_ZLIB_WINDOW_BITS 15 

#define DO_HOST_LOOKUP 0

#define DO_MOTD 0
#define MOTD_FILENAME "/etc/motd"

#define DROPBEAR_SVR_PASSWORD_AUTH 0
#define DROPBEAR_SVR_PAM_AUTH 0
#define DROPBEAR_SVR_PUBKEY_AUTH 1
#define DROPBEAR_SVR_PUBKEY_OPTIONS 1

#define DROPBEAR_SVR_MULTIUSER 1

#define DROPBEAR_CLI_PASSWORD_AUTH 1
#define DROPBEAR_CLI_PUBKEY_AUTH 1

#define DROPBEAR_DEFAULT_CLI_AUTHKEY "~/.ssh/ssh"

#define DROPBEAR_USE_PASSWORD_ENV 0
#define DROPBEAR_CLI_ASKPASS_HELPER 0

#define DROPBEAR_CLI_IMMEDIATE_AUTH 0

#define DROPBEAR_USE_PRNGD 0
#define DROPBEAR_PRNGD_SOCKET "/run/prngd"

#define MAX_UNAUTH_PER_IP 5
#define MAX_UNAUTH_CLIENTS 30
#define MAX_AUTH_TRIES 10
#define UNAUTH_CLOSE_DELAY 0

#define DROPBEAR_PIDFILE "~/.ssh/pid"

#define XAUTH_COMMAND "/usr/bin/xauth -q"

#define DROPBEAR_SFTPSERVER 1
#define SFTPSERVER_PATH "/sbin/sftp-server"
#define DROPBEAR_PATH_SSH_PROGRAM "/bin/dbclient"

#define LOG_COMMANDS 0

#define DEFAULT_RECV_WINDOW 1024000
#define RECV_MAX_PAYLOAD_LEN 32768
#define TRANS_MAX_PAYLOAD_LEN 16384

#define DEFAULT_KEEPALIVE 60
#define DEFAULT_KEEPALIVE_LIMIT 3
#define DEFAULT_IDLE_TIMEOUT 0

#define DEFAULT_PATH "/bin:/sbin:/usr/bin:/usr/sbin"
#define DEFAULT_ROOT_PATH "/bin:/sbin:/usr/bin:/usr/sbin"

#endif

