#!/usr/bin/sh
#############
. /etc/services/p2pd/install
#############
pgrep -x p2pd &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
setsid su -l -s /usr/bin/sh -c "p2pd --config-dir ${service_storage}/.config </dev/null &>/dev/null & exit" p2pd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +5 -u "p2pd"
#############
