#!/bin/sh
#############
. /etc/services/p2pd/install
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/ash -c "exec p2pd --config-dir ${service_storage}/.config </dev/null &>/dev/null & exit" p2pd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +10 -u "p2pd"
#############
