#!/usr/bin/sh
#############
usage(){ printf "\n${0} - ${1}\n\n -c host:port\n -u udp\n -t tcp\n\n" ; exit 1 ; }
#############
while getopts "c:ut" arg;do
 case "${arg}" in
  c) connect="${OPTARG}" ;;
  u) protocol="-dtls1_2" ;;
  t) protocol="-tls1_3" ;;
  *) usage getopts ;;
 esac
done
#############
[ -z "${connect}" ] && usage "requires host:port"
[ -z "${protocol}" ] && usage "requires protocol"
#############
openssl s_client -connect "${connect}" \
 -key "${HOME}/.ssl/token.pem" \
 -cert "${HOME}/.ssl/token.crt" \
 -chainCAfile "${HOME}/.ssl/client.crt" -build_chain \
 -verifyCAfile "${HOME}/.ssl/server.crt" \
 -no-CAfile -no-CApath -no-CAstore \
 -verify 1 -verify_return_error -verify_quiet -quiet \
 -ignore_unexpected_eof -ign_eof ${protocol}
#############
