#!/usr/bin/sh
#############
usage(){ printf "\n${0} - ${1}\n\n -p port\n -u udp\n -t tcp\n\n" ; exit 1 ; }
#############
while getopts "p:ut" arg ; do
 case "${arg}" in
  p) port="${OPTARG}" ;;
  u) protocol="-dtls1_2" ;;
  t) protocol="-tls1_3" ;;
  *) usage getopts ;;
 esac
done
#############
[ -z "${port}"     ] && usage "requires port"
[ -z "${protocol}" ] && usage "requires protocol"
#############
openssl s_server -port ${port}\
 -dhparam "${HOME}/.ssl/dhparam" \
 -key "${HOME}/.ssl/service.pem" \
 -cert "${HOME}/.ssl/service.crt" \
 -chainCAfile "${HOME}/.ssl/server.crt" -build_chain \
 -verifyCAfile "${HOME}/.ssl/client.crt" \
 -no-CAfile -no-CApath -no-CAstore \
 -Verify 1 -verify_return_error -verify_quiet -quiet \
 -ignore_unexpected_eof -ign_eof ${protocol}
#############
