#!/usr/bin/sh
#############
usage(){ printf "%s\n" "takes interface - ${1}" ; exit 1 ; }
#############
[ "${USER}" == "root" ] || usage "requires root"
[ "${#}" == "1" ] || usage "no input"
[ -d "/sys/class/net/${1}" ] || usage "interface does not exist"
#############
pkill -x /usr/sbin/udhcpc
#############
ip link set up "${1}"
#############
env -i /usr/sbin/udhcpc -vSnqfa2000 -i "${1}" -s /usr/bin/udhcpc_default
#############
