#!/bin/sh
#############
usage(){ printf "%s\n" "ntp client - ${1}" ; exit 1 ; }
#############
[ "${#}" == "0" ] && ntpd -dnqN -p 0.pool.ntp.org -p 1.pool.ntp.org -p 2.pool.ntp.org -p 3.pool.ntp.org
#############
[ "${#}" == "1" ] && ntpd -dnqN -p "${1}"
#############
[ "${#}" == "2" ] && ntpd -dnqN -p "${1}" -p "${2}"
#############
[ "${#}" == "3" ] && ntpd -dnqN -p "${1}" -p "${2}" -p "${3}"
#############
[ "${#}" == "4" ] && ntpd -dnqN -p "${1}" -p "${2}" -p "${3}" -p "${4}"
#############
