#!/usr/bin/sh
#############
[ -z "${1}" ] && busybox --list-full | while read ; do ln -s "/usr/bin/busybox" "/usr/${REPLY}" ; done
#############
[ -z "${1}" ] || busybox --list-full | while read ; do ln -s "/usr/bin/busybox" "${1}/usr/${REPLY}" ; done
#############
