#!/usr/bin/sh
#############
[ "${1}" == "bound" ] || return 1
#############
[ -z "${interface}" ] || [ -z "${ip}" ] || [ -z "${mask}" ] || [ -z "${router}" ] && return 1
#############

#############
ip link set down dev "${interface}"
ip addr flush dev "${interface}"
ip link set up dev "${interface}"
#############
[ -z "${broadcast}" ] && ip addr add "${ip}/${mask}" dev "${interface}"
[ -z "${broadcast}" ] || ip addr add "${ip}/${mask}" broadcast "${broadcast}" dev "${interface}"
[ -z "${router}" ] || ip route del default
[ -z "${router}" ] || ip route add default via "${router}" dev "${interface}" scope global metric 0
#############
[ -z "${opt96}" ] || ip addr add "${opt96}::${ip//./:}/64" dev "${interface}"
[ -z "${opt96}" ] || ip -6 route del default
[ -z "${opt96}" ] || ip -6 route add default via "${opt96}::${router//./:}" dev "${interface}" scope global metric 0
#############
[ -z "${dns}" ] || ln -sf /run/resolv.conf /etc/resolv.conf
[ -z "${dns}" ] || install -o 0 -g 0 -m 0664 /dev/null /run/resolv.conf
[ -z "${dns}" ] || printf "%s\n" "search localdomain" >> /run/resolv.conf
[ -z "${dns}" ] || printf "%s\n" "options edns0" >> /run/resolv.conf # no-aaaa
[ -z "${dns}" ] || for i in ${dns} ; do printf "%s\n" "nameserver ${i}" >> /run/resolv.conf ; done
#############

#############
storage="/tmp/storage" ; [ -d "${storage}" ] || return 0
install -d -o 0 -g 0 -m 0775 "${storage}/.net"
install -o 0 -g 0 -m 0600 "/dev/null" "${storage}/.net/dhcpc"
printf "%s\n" "export opt96='${opt96}'" >> "${storage}/.net/dhcpc"
printf "%s\n" "export interface='${interface}'" >> "${storage}/.net/dhcpc"
printf "%s\n" "export ip='${ip}'" >> "${storage}/.net/dhcpc"
printf "%s\n" "export mask='${mask}'" >> "${storage}/.net/dhcpc"
printf "%s\n" "export router='${router}'" >> "${storage}/.net/dhcpc"
printf "%s\n" "export broadcast='${broadcast}'" >> "${storage}/.net/dhcpc"
printf "%s\n" "export dns='${dns}'" >> "${storage}/.net/dhcpc"
chown root:root "${storage}/.net/dhcpc" ; chmod 0600 "${storage}/.net/dhcpc"
#############

