#!/usr/bin/sh
#############
usage(){ printf "%s\n" "takes interface and or hostname - ${1}" ; exit 1 ; }
#############
[ "${#}" == "1" ] || [ "${#}" == "2" ] || usage "no input"
#############
[ -d "/sys/class/net/${1}" ] || usage "interface does not exist"
#############
[ -z "${2}" ] || hostname="-xhostname:${2}"
#############
pkill -x /usr/sbin/udhcpc
#############
ip link set up "${1}"
#############

install -d -o 68 -g 68 -m 0775 /run/udhcpc
install    -o 68 -g 68 -m 0664 /dev/null /run/resolv.conf

cd / ; caps="-all,+net_admin,+net_raw,+net_bind_service"

/usr/bin/setsid /usr/bin/setpriv \
 --reuid dhcpc --regid dhcpc --init-groups --nnp --reset-env \
 --inh-caps "${caps}" --ambient-caps "${caps}" --bounding-set "${caps}" \
 /usr/sbin/udhcpc -vSnqfa2000 -i "${1}" -s /usr/bin/udhcpc_default "${hostname}" < /dev/null

#############
renice -5 -u "dhcpc"
#############
if [ "${1}" == "nat" ]
then

 ip route add 224.0.0.0/4 dev nat scope link metric 0
 ip route add 169.254.0.0/16 dev nat scope link metric 0

fi
#############

