#!/usr/bin/sh
#############
pkill -x /usr/bin/udpsvd
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
#############
cd / ; caps="-all,+sys_chroot,+net_bind_service" ; /usr/bin/setsid /usr/bin/setpriv \
 --reuid tftpd --regid tftpd --init-groups --nnp --reset-env \
 --inh-caps "${caps}" --ambient-caps "${caps}" --bounding-set "${caps}" \
 /usr/bin/udpsvd 0.0.0.0 69 /usr/sbin/tftpd -lr /tmp/storage/shared </dev/null &>/dev/null & sleep 1
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice -5 -u "tftpd"
#############
