#!/bin/sh
#############
usage(){ printf "%s\n" "takes interface - ${1}" ; exit 1 ; }
#############
[ "${#}" == "1" ] || usage "no input"
#############
[ -d "/sys/class/net/${1}" ] || usage "interface does not exist"
#############

#############
pkill -x /sbin/zcip
#############
ip link set up "${1}"
#############




cd / ; caps="-all,+net_admin,+net_raw,+net_bind_service"

/bin/setsid /usr/bin/setpriv \
 --reuid dhcpd --regid dhcpd --init-groups --nnp --reset-env \
 --inh-caps "${caps}" --ambient-caps "${caps}" --bounding-set "${caps}" \
 /sbin/zcip -vfq "${1}" /bin/udhcpc_zcip < /dev/null

#############
renice -5 -u "dhcpd"
#############

