#!/bin/sh
#############
[ "${1}" == "bound" ] || return 1
#############
[ -z "${interface}" ] || [ -z "${ip}" ] || [ -z "${subnet}" ] || [ -z "${router}" ] && return 1
#############













#############

#############

ip link set down dev "${interface}"
ip addr flush dev "${interface}"

[ -z "${broadcast}" ] && ip addr add "${ip}/${subnet}" dev "${interface}"
[ -z "${broadcast}" ] || ip addr add "${ip}/${subnet}" broadcast "${broadcast}" dev "${interface}"

ip link set up "${interface}"




#############
[ -z "${opt96}" ] || ip addr add "${opt96}::${ip//./:}/64" dev "${interface}"


#############

#############

#############


#############

#############

 install -d -o 68 -g 68 -m 0775 "/run/udhcpc" "/run/udhcpc/${interface}"

 printf "%s\n" "${broadcast##* }" > "/run/udhcpc/${interface}/broadcast"
           printf "%s\n" "${dns}" > "/run/udhcpc/${interface}/dns"
        printf "%s\n" "${domain}" > "/run/udhcpc/${interface}/domain"
        printf "%s\n" "${router}" > "/run/udhcpc/${interface}/gateway"
      printf "%s\n" "${hostname}" > "/run/udhcpc/${interface}/hostname"
            printf "%s\n" "${ip}" > "/run/udhcpc/${interface}/ip"
         printf "%s\n" "${lease}" > "/run/udhcpc/${interface}/lease"
          printf "%s\n" "${mask}" > "/run/udhcpc/${interface}/mask"
        printf "%s\n" "${ntpsrv}" > "/run/udhcpc/${interface}/ntpsrv"

 find /run/udhcpc -type d -exec chmod 0775 {} \;
 find /run/udhcpc -type f -exec chmod 0664 {} \;

#############

