#!/bin/sh
#############

name="binutils"
version="2.31"

build="binutils-2.31"

source="binutils-2.31.tar.xz"
signature="binutils-2.31.tar.xz.sig"
public="gnu-keyring.gpg"

link_source="https://ftp.gnu.org/gnu/binutils/binutils-2.31.tar.xz"
link_signature="https://ftp.gnu.org/gnu/binutils/binutils-2.31.tar.xz.sig"
link_public="https://ftp.gnu.org/gnu/gnu-keyring.gpg"

package="binutils.tar.gz"

#############
