#!/bin/sh
#############

name="gcc"
version="8.2.0"
source="gcc-8.2.0.tar.xz"
signature="gcc-8.2.0.tar.xz.sig"
checksum="gcc-8.2.0.tar.xz.checksum"
public_key="https://ftp.gnu.org/gnu/gnu-keyring.gpg"
package="gcc-8.2.0.tar.gz"

link_package="https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz"
link_signature="https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz.sig"



#############
download(){

 [ "${link_package}" == ""   ] || [ -x "${downloads}/${source}"    ] || curl --progress-bar -o "${downloads}/${source}" "${link_package}"
 [ "${link_signature}" == "" ] || [ -x "${downloads}/${signature}" ] || curl --progress-bar -o "${downloads}/${source}" "${link_signature}"

 [ "${link_package}" == ""   ] || [ -x "${downloads}/${source}"    ] && debug="${debug}[${g}${source}${m}]\n"    || debug="${debug}[${r}${source}${m}]\n"
 [ "${link_signature}" == "" ] || [ -x "${downloads}/${signature}" ] && debug="${debug}[${g}${signature}${m}]\n" || debug="${debug}[${r}${signature}${m}]\n"

 [ "${link_package}" == ""   ] || [ -x "${downloads}/${source}"    ] || die
 [ "${link_signature}" == "" ] || [ -x "${downloads}/${signature}" ] || die

 gpg --trust-model always --verify "${downloads}/${signature}" &>/dev/null && debug="${debug}[${g}verify${m}]" || debug="${debug}[${r}verify${m}]"
 gpg --trust-model always --verify "${downloads}/${signature}" &>/dev/null || die

}
#############




