#!/bin/sh
#############

name="mpc"
version="1.1.0"
source="mpc-1.1.0.tar.gz"
signature="mpc-1.1.0.tar.gz.sig"
checksum="mpc-1.1.0.tar.gz.checksum"
public_key="https://ftp.gnu.org/gnu/gnu-keyring.gpg"
package="mpc-1.1.0.tar.gz"

link_package="https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz"
link_signature="https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz"

#############
