#!/usr/bin/sh
#############
for i in "${service_storage}" "${service_tmp}"
do
 chown -R "${1}":"${2}" "${i}"
 find "${i}" -type d -exec chmod "${3}" {} \;
 find "${i}" -type f -exec chmod "${4}" {} \;
done
#############
