#!/usr/bin/sh
#############
export services_system="/etc/services"
export services_storage="/tmp/storage/services"
export services_tmp="/run/services"
#############
export service_system="${services_system}/${1}/files"
export service_storage="${services_storage}/${1}"
export service_tmp="${services_tmp}/${1}"
#############
for i in "${services_storage}" "${services_tmp}" ; do install -d -o 0 -g 0 -m 0775 "${i}" ; done
for i in "${service_storage}" "${service_tmp}" ; do install -d -o 0 -g 0 -m 0700 "${i}" ; done
#############
