#!/bin/sh
#############
set -o pipefail
#############
log="/run/logs/syslog"
logs="/run/logs/syslog.2 /run/logs/syslog.1 /run/logs/syslog.0 /run/logs/syslog"
filter="\sforward\.|\sinput\.|\soutput\."
prefix="\sforward\.[^ ]+|\sinput\.[^ ]+|\soutput\.[^ ]+"
column="\sIN=[^ ]+|\sOUT=[^ ]+|\sSRC=[^ ]+|\sDST=[^ ]+|\sPROTO=[^ ]+|\sTYPE=[^ ]+|\sSPT=[^ ]+|\sDPT=[^ ]+|\sUID=[^ ]+|\sGID=[^ ]+"
#############
[ "${#}" == "0" ] && grep -E "${filter}" ${logs} | while read -r ; do printf "%s\n" "${REPLY}" | grep -hoE "${prefix}|${column}" | tr -d '\n' && echo '' ; done
[ "${#}" == "1" ] && tail -F ${log} | while read -r ; do printf "%s\n" "${REPLY}" | grep -E "${filter}" | grep -hoE "${prefix}|${column}" | tr -d '\n' && echo '' ; done
#############
