#!/usr/bin/sh
#############

#mountpoint -q "${stage3}" && exec dtach -A "${stage3}/.socket" /usr/bin/sh -l

#############

#############

[ -f "${mount}/stage3" ] || { qemu-img create -f raw "${mount}/stage3" 47G
                              mkfs.ext4 -m 0 -L "stage3" "${mount}/stage3" ; }

#############

 losetup "/dev/loop0" "${mount}/stage3" 
 fsck.ext4 -pvf "/dev/loop0"

 fsck.ext4 -pv "/dev/loop0" &&
 install -d -o 0 -g 0 -m 0700 "${stage3}" &&
 mount -t ext4 -o rw,dev,nosuid,exec,noatime "/dev/loop0" "${stage3}" &&
 install -d -o 0 -g 0 -m 0700 "${stage3}" ||
 { umount "${stage3}" ; exit 1 ; }

 rmdir "${stage3}/lost+found"

#############

#exec dtach -A "${stage3}/.socket" /usr/bin/sh -l

#############

