#!/bin/sh
#############
cd / ; install -o 67 -g 67 -m 0600 /dev/null /run/leases
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
#############
/usr/bin/setpriv \
 --reuid dhcpd --regid dhcpd --init-groups \
 --inh-caps -all,+net_raw \
 --ambient-caps -all,+net_raw \
 --bounding-set -all,+net_raw \
 --nnp --reset-env \
 /sbin/udhcpd -S </dev/null &>/dev/null ; sleep 1
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
