#!/bin/sh
#############
cd / ; install -d -o 68 -g 68 -m 0644 /dev/null /run/udhcpc ; install    -o 68 -g 68 -m 0644 /dev/null /run/resolv.conf
#############

#############
/usr/bin/setpriv \
 --reuid dhcpc --regid dhcpc --init-groups \
 --inh-caps -all,+net_bind_service,+net_raw,+net_admin \
 --ambient-caps -all,+net_bind_service,+net_raw,+net_admin \
 --bounding-set -all,+net_bind_service,+net_raw,+net_admin \
 --nnp --reset-env \
 /sbin/udhcpc -vSba2000 -i "${1}" -s /etc/self/setpriv/setpriv_udhcpc_persist -x "hostname:${2:- na}"
#############

#############
