#!/bin/sh
#############
cd /
#############

#############
/usr/bin/setpriv \
 --reuid ntpd --regid ntpd --init-groups \
 --inh-caps -all,+sys_time \
 --ambient-caps -all,+sys_time \
 --bounding-set -all,+sys_time \
 --nnp --reset-env \
 /sbin/ntpd -dnqN -p 0.pool.ntp.org -p 1.pool.ntp.org -p 2.pool.ntp.org -p 3.pool.ntp.org
#############

#############
