#!/bin/sh
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
#############
su -l -s /bin/ash -c 'exec ntpd -l </dev/null &>/dev/null & exit' ntpd ; sleep 1
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
