#!/bin/sh
#############
. /etc/services/variables dnsd
#############
[ -f "${service_storage}/config" ] || install -o dnsd -g dnsd -m 0600 "${service_system}/config" "${service_storage}/config"
#############
printf "%s\n" "search localdomain" > /etc/resolv.conf
printf "%s\n" "options edns0 no-aaaa" >> /etc/resolv.conf
printf "%s\n" "nameserver 127.0.0.1" >> /etc/resolv.conf
chown root:root /etc/resolv.conf ; chmod 0664 /etc/resolv.conf
#############
. /etc/services/permissions dnsd dnsd 0700 0600
#############
