#!/bin/sh
#############
. /etc/services/dnsd/install
#############
pgrep -x dnsd &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/ash -c "setsid dnsd -f ${service_storage}/config </dev/null &>/dev/null & exit" dnsd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice -10 -u "dnsd"
#############
