#!/bin/sh
#############
cd /tmp/a.bootfs || exit ; echo '#############'
#############
openssl sha256 EFI/boot/bootx64.efi | tee hashes ; echo '#############'
#############
for i in .client client ; do openssl sha256 images/${i} | tee -a hashes ; done ; echo '#############'
#############
for i in .desktop .laptop .server .virtual desktop laptop server virtual ; do openssl sha256 kernels/${i} | tee -a hashes ; done ; echo '#############'
#############
openssl sha256 binhost.tar.gz | tee -a hashes ; echo '#############'
#############
openssl sha256 config.tar.gz | tee -a hashes ; echo '#############'
#############
openssl sha256 config.torrent | tee -a hashes ; echo '#############'
#############
