
#############

server_names = []

max_clients = 250

listen_addresses = ['127.0.0.1:53','172.16.0.1:53']

user_name = ''

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = true

require_dnssec = true
require_nolog = true
require_nofilter = true

disabled_server_names = []

force_tcp = false
http3 = false
proxy = ''
http_proxy = ''

timeout = 500 #5000
keepalive = 60 #30

edns_client_subnet = []
blocked_query_response = 'refused'
lb_strategy = 'p2'
lb_estimator = true

log_level = 2
log_file = ''
log_file_latest = false

use_syslog = true

cert_refresh_delay = 240

cert_ignore_timestamp = false

dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false

## 49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
## 49195 = TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
## 52392 = TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
## 52393 = TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
tls_cipher_suite = [52393,49195]

tls_key_log_file = ''

bootstrap_resolvers = ['1.1.1.1:53','8.8.8.8:53']

ignore_system_dns = true

netprobe_timeout = 60

netprobe_address = '1.1.1.1:53'

offline_mode = false

query_meta = []

log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

#############
 block_ipv6 = true
 block_unqualified = true
 block_undelegated = true
 reject_ttl = 10
#############
 forwarding_rules = 'forwarding-rules.txt'
#############
#cloaking_rules = '/etc/hosts'
 cloak_ttl = 600
 cloak_ptr = true
#############
 cache = true
 cache_size = 4096
 cache_min_ttl = 2400
 cache_max_ttl = 86400
 cache_neg_min_ttl = 60
 cache_neg_max_ttl = 600
#############

[captive_portals]

 map_file = ''

[local_doh]

 listen_addresses = []
 path = '/dns-query'
 cert_file = ''
 cert_key_file = ''

#############

[query_log]

 file = 'logs/query.log'
 format = 'tsv'
 ignored_qtypes = []

[nx_log]

 file = 'logs/nx.log'
 format = 'tsv'

[blocked_names]

 blocked_names_file = ''
 log_file = ''
 log_format = 'tsv'

[blocked_ips]

 blocked_ips_file = ''
 log_file = ''
 log_format = 'tsv'

[allowed_names]

 allowed_names_file = ''
 log_file = ''
 log_format = 'tsv'

[allowed_ips]

 allowed_ips_file = ''
 log_format = ''
 log_file = ''

#############

[schedules]

#############

[sources]

 [sources.public-resolvers]
  urls = ['https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
  cache_file = 'resolvers/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

 [sources.relays]
  urls = ['https://download.dnscrypt.info/resolvers-list/v3/relays.md']
  cache_file = 'resolvers/relays.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

 #[sources.odoh-servers]
 # urls = ['https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
 # cache_file = 'resolvers/odoh-servers.md'
 # minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
 # refresh_delay = 24
 # prefix = ''

 #[sources.odoh-relays]
 # urls = ['https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
 # cache_file = 'resolvers/odoh-relays.md'
 # minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
 # refresh_delay = 24
 # prefix = ''

#############

[broken_implementations]

 fragments_blocked = []

[doh_client_x509_auth]

 creds = []

[anonymized_dns]

 routes = [ { server_name='*', via=['*'] } ]
 skip_incompatible = false
 direct_cert_fallback = true

[dns64]

prefix = []
resolver = []

[static]

#############

