#!/bin/sh
#############
. /etc/services/crond/install
#############
pgrep -x crond &>/dev/null && exit
#############

(setsid crond -bSc "${service_storage}" </dev/null &>/dev/null & exit) ; sleep 1

#############
renice -10 -u "root"
#############
