#!/bin/sh
#############
usage(){ printf "%s\n" "takes initramfs and rootfs full paths (from - > to) - ${1}" ; exit 1 ; }
#############
[ "${#}" == "2" ] || usage "no input"
#############
[ -f "${1}" ] || usage "initramfs does not exist"
[ -e "${2}" ] && usage "rootfs already exists"
[ -e "${2}" ] || install -d -o 0 -g 0 -m 0775 "${2}"
#############
cd "${2}" && gzip -cd "${1}" | cpio -id
#############
