#!/usr/bin/sh
#############
usage(){ printf "%s\n" "takes interface and or hostname - ${1}" ; exit 1 ; }
#############
[ "${#}" == "1" ] || [ "${#}" == "2" ] || usage "no input"
#############
[ -d "/sys/class/net/${1}" ] || usage "interface does not exist"
#############
[ -z "${2}" ] || hostname="-xhostname:${2}"
#############
pkill -x /usr/sbin/udhcpc
#############
ip link set up "${1}"
#############
env -i /usr/sbin/udhcpc -vSnqfa2000 -i "${1}" -s /usr/bin/udhcpc_default "${hostname}"
#############
