#!/bin/sh
#############
[ "${1}" == "config" ] || return 0
#############
[ -z "${interface}" ] || [ -z "${ip}" ] && return 0
#############
printf "%s\n" "
#############
interface: ${interface}
#############
ip: ${ip}
#############
"
#############
read -rp 'continue ?'
#############
ip addr add scope link "${ip}/16" broadcast "169.254.255.255" dev "${interface}"
#############
