#!/bin/sh
#############
[ "${1}" == "bound" ] || return 1
#############
[ -z "${ipv6}" ] && return 1
#############
printf "%s\n" "
#############
# ${1}
#############
$(env)
#############
"
#############
read -rp 'continue ?'
#############

ip link set up "lan"

ip addr add "${ipv6}/64" dev lan

#############
