#!/bin/sh
#############
. /etc/services/nfsd/install
#############
exportfs -rv
exportd -s "${service_storage}"
nfsd -N3 -V4 -N4.1 -N4.2 --no-udp --tcp --host 0.0.0.0 --port 2049 --syslog $(grep -c MHz /proc/cpuinfo)
#############
renice -10 -i "nfsd"
#############
