#!/usr/bin/sh
#############
usage(){ printf "%s\n" "takes interface - ${1}" ; exit 1 ; }
#############
[ "${USER}" == "root" ] || usage "requires root"
[ "${#}" == "1" ] || usage "no input"
[ -d "/sys/class/net/${1}" ] || usage "interface does not exist"
#############
pkill -x /usr/sbin/zcip
#############
ip link set up "${1}"
#############

cd /

caps="-all,+net_admin,+net_raw"

/usr/bin/setsid /usr/bin/setpriv \
 --reuid dhcpc \
 --regid dhcpc \
 --init-groups \
 --nnp \
 --reset-env \
 --inh-caps "${caps}" \
 --ambient-caps "${caps}" \
 --bounding-set "${caps}" \
 /usr/sbin/zcip -vfq "${1}" /usr/bin/udhcpc_zcip < /dev/null

#############

