#!/usr/bin/sh
#############
pkill -x /usr/sbin/ntpd
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
setsid su -l -s /usr/bin/sh -c '/usr/sbin/ntpd -l </dev/null &>/dev/null & exit' ntpd ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice -5 -u "ntpd"
#############
