#!/usr/bin/sh
#############
usage(){ printf "%s\n" "takes interface - ${1}" ; exit 1 ; }
#############
[ "${USER}" == "root" ] || usage "requires root"
[ "${#}" == "1" ] || usage "no input"
[ -d "/sys/class/net/${1}" ] || usage "interface does not exist"
[ -f "${storage}/.net/address" ] && mv "${storage}/.net/address" "${storage}/.net/.address"
[ -f "${storage}/.net/dhcpc" ] && mv "${storage}/.net/dhcpc" "${storage}/.net/.dhcpc"
#############
pkill -x /usr/sbin/udhcpc
#############
ip link set down dev "${1}"
ip addr flush dev "${1}"
random(){ hexdump -n6 -ve '1/1 "%02X:"' /dev/urandom | head -c17 ; }
until ip link set dev "${1}" address "$(random)" ; do sleep .1 ; done
install -o 68 -g 68 -m 0664 "/sys/class/net/${1}/address" "${storage}/.net/address"
ip link set up dev "${1}"
#############
sysctl -w "net.ipv6.conf.${1}.autoconf=1"
sysctl -w "net.ipv6.conf.${1}.accept_ra=2"
#############

install -o 68 -g 68 -m 0664 "/dev/null" "${storage}/.net/dhcpc"
install -o 68 -g 68 -m 0664 "/dev/null" "/run/resolv.conf"

cd /

caps="-all,+net_admin,+net_raw"

/usr/bin/setsid /usr/bin/setpriv \
 --reuid dhcpc \
 --regid dhcpc \
 --init-groups \
 --nnp \
 --reset-env \
 --inh-caps "${caps}" \
 --ambient-caps "${caps}" \
 --bounding-set "${caps}" \
 /usr/sbin/udhcpc -vSnqfa2000 -i "${1}" -s /usr/bin/udhcpc_dhcpc < /dev/null

#############

[ "${1}" == "nat" ] && {

 ip route add 224.0.0.0/4 dev nat scope link metric 0
 ip route add 169.254.0.0/16 dev nat scope link metric 0

}

#############

