#!/bin/sh
#############
[ "${USER}" == "root" ] || exit 1
#############
[ -f "/tmp/.X0-lock" ] && exit 1
#############
install -o desktop -g desktop -m 0640 /dev/null /tmp/.X0-log
install -o desktop -g desktop -m 0640 /dev/null /tmp/.X0-log.old
install -o desktop -g desktop -m 0640 /dev/null /tmp/.X0-auth
printf "%s\n" "add :0 . $(hexdump -n16 -ve '1/1 "%02x"' /dev/urandom)" | xauth -nqf /tmp/.X0-auth
chown "desktop:toor" /tmp/.X0-auth
chmod 0640 /tmp/.X0-auth
#############

su -l -s /bin/ash desktop << EOF
DISPLAY=:0 XAUTHORITY=/tmp/.X0-auth \
setsid xinit /etc/xinitrc -- /usr/bin/X \
-extension 'Generic Event Extension' \
-extension 'MIT-SHM' \
-extension 'XTEST' \
-extension 'XINERAMA' \
-extension 'XFIXES' \
+extension 'RENDER' \
+extension 'RANDR' \
-extension 'COMPOSITE' \
-extension 'DAMAGE' \
-extension 'MIT-SCREEN-SAVER' \
-extension 'DOUBLE-BUFFER' \
-extension 'RECORD' \
-extension 'DPMS' \
-extension 'X-Resource' \
-extension 'XVideo' \
-extension 'XVideo-MotionCompensation' \
-s 0 -auth /tmp/.X0-auth -logfile /tmp/.X0-log \
-nolisten tcp -nolisten unix -listen local \
vt7 :0 </dev/null &>/dev/null & exit
EOF

#############

until [ -f /tmp/.X0-lock ] ; do sleep 1 ; done

#############

su -l -s /bin/ash -c 'DISPLAY=:0 XAUTHORITY=/tmp/.X0-auth setsid dwm-host </dev/null &>/dev/null & exit' toor

#############

