#!/bin/sh
#############
. /etc/services/ircd/install
#############
pgrep -x ngircd &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
ngircd --config "${service_storage}/ngircd.conf" ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +10 -u "ircd"
#############
