#!/bin/sh
#############
umask 077

############# cleanup

rm -r /etc/hotplug.d
rm -r /etc/modules-boot.d
rm -r /etc/modules.d
rm -r /etc/rc.d
rm -r /etc/sysctl.d

rm -r /lib/netifd
rm -r /lib/wifi

rm -r /usr/bin

rm -r /usr/lib/opkg

rm -r /var

############# ulimit
ulimit -f 14680064  # file size (blocks)
ulimit -t unlimited # cpu time (seconds)
ulimit -d unlimited # data seg size (kb)
ulimit -s 8192      # stack size (kb)
ulimit -c 0         # core file size (blocks)
ulimit -m unlimited # resident set size (kb)
ulimit -l 64        # locked memory (kb)
ulimit -p 23        # processes
ulimit -n 1024      # file descriptors
ulimit -v unlimited # address space (kb)
ulimit -w unlimited # locks
ulimit -e 0         # scheduling priority
ulimit -r 0         # real-time priority

############# filesystem
mount -t proc -o rw,nodev,nosuid,noexec,noatime,hidepid=2 proc /proc
mount -o remount,hidepid=2 /proc
mount -t sysfs -o rw,nodev,nosuid,noexec,noatime sysfs /sys
mount -t devtmpfs -o rw,dev,nosuid,noexec,noatime devtmpfs /dev
mkdir -p /dev/pts
mount -t devpts -o ro,dev,nosuid,noexec,noatime,mode=0600 devpts /dev/pts
mount -t tmpfs -o rw,nodev,nosuid,noexec,noatime tmpfs /tmp
#############
mount -o remount,ro,nosuid,size="$(df|awk 'NR==2{print$3}')k" /

############# # modules - hahahahahahahahahahahaha seriously tho
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done

############# logs
syslogd -SDC1000
klogd

############# sysctl
sysctl -p /etc/sysctl.conf

############# # network

echo 'openwrt' > /proc/sys/kernel/hostname
echo 'localdomain' > /proc/sys/kernel/domainname

nft -f /etc/nftables.rules

ip addr add 127.0.0.1/8 dev lo brd + scope host
ip route add 127.0.0.0/8 dev lo scope host
ip link set up lo

ip link set up eth0
ip addr add 192.168.3.1/24 dev eth0
ip addr add fd03::1/64 dev eth0

ip link set up wlan0
ip addr add 192.168.1.1/24 dev wlan0
ip addr add fd01::1/64 dev wlan0

hostapd -B /etc/hostapd

############# # services
touch /tmp/leases
chown 67:67 /tmp/leases
chmod 600 /tmp/leases
#############
telnetd -b 192.168.3.1:23 -f /etc/banner -l /sbin/ffs
dnsd -dc /etc/dnsd -i 192.168.1.1 -p 53
udhcpd -S /etc/udhcpd-lan
udhcpd -S /etc/udhcpd-man
radvd -C /etc/radvd.conf -u udhcpd -p /tmp/radvd.pid

############# # gpio
printf "%s\n" "11" > /sys/class/gpio/export
buttons

