#!/bin/sh
#############
. /etc/services/smtpd/install
#############
pgrep -x smtpd &>/dev/null && exit
#############

setsid smtpd -f "${service_storage}/smtpd.conf" </dev/null &>/dev/null

#############
until [ -S "${service_storage}/smtpd.sock" ] ; do sleep .3 ; done
#############
renice +10 -u "smtpd"
renice +10 -u "smtpq"
#############
