#!/bin/sh
#############
. /etc/services/variables dnscrypt
#############
[ -d "${service_storage}/logs" ] || install -d -o 53 -g 53 -m 0700 "${service_storage}/logs"
[ -d "${service_storage}/resolvers" ] || install -d -o 53 -g 53 -m 0700 "${service_storage}/resolvers"
[ -f "${service_storage}/dnscrypt-proxy.toml" ] || install -o 53 -g 53 -m 0600 "${service_system}/files/dnscrypt-proxy.toml" "${service_storage}"
[ -f "${service_storage}/forwarding-rules.txt" ] || install -o 53 -g 53 -m 0600 "${service_system}/files/forwarding-rules.txt" "${service_storage}"
#############
printf "%s\n" "nameserver 127.0.0.1" > /etc/resolv.conf
chown root:root /etc/resolv.conf
chmod 0664 /etc/resolv.conf
#############
. /etc/services/permissions dnscrypt dnscrypt 0700 0600
#############
