#!/bin/sh
#############
. /etc/services/variables dnsd
#############

[ -d "${service_storage}/logs"                ] || install -d -o dnsd -g dnsd -m 2770 "${service_storage}/logs"
[ -f "${service_storage}/dnscrypt-proxy.toml" ] || install    -o dnsd -g dnsd -m 0660 "${service_system}/files/dnscrypt-proxy.toml" "${service_storage}"
[ -f "${service_storage}/hosts"               ] || install    -o dnsd -g dnsd -m 0660 "${service_system}/files/hosts"               "${service_storage}"
[ -f "${service_storage}/blacklist.ip"        ] || install    -o dnsd -g dnsd -m 0660 "${service_system}/files/blacklist.ip"        "${service_storage}"
[ -f "${service_storage}/blacklist.domain"    ] || install    -o dnsd -g dnsd -m 0660 "${service_system}/files/blacklist.domain"    "${service_storage}"




#############
. /etc/services/permissions dnsd dnsd 2770 0660
#############
