#!/bin/sh
#############
. /etc/services/dnscrypt/install
#############
pgrep -x dnscrypt-proxy &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/ash -c "setsid dnscrypt-proxy --config ${service_storage}/dnscrypt-proxy.toml </dev/null &>/dev/null & exit" dnscrypt ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice -10 -u "dnscrypt"
#############
