#!/bin/sh
#############
. /etc/services/dnsd/install
#############
su -ls /bin/sh -c "exec dnscrypt-proxy --config ${service_storage}/dnscrypt-proxy.toml --pidfile ${service_storage}/pid </dev/null &>/dev/null &" dnsd
#############
printf "%s\n" "nameserver 127.0.0.1" > /etc/resolv.conf
chown root:root /etc/resolv.conf
chmod 0644 /etc/resolv.conf
#############
