#!/bin/sh
#############
umask 077
#############
install -d -o root -g root -m 0700 "/dev";     mount -t devtmpfs -o rw,dev,nosuid,noexec,noatime,size=0%             devtmpfs "/dev"
install -d -o root -g root -m 0700 "/dev/pts"; mount -t devpts   -o ro,dev,nosuid,noexec,noatime,mode=0600           devpts   "/dev/pts"
install -d -o root -g root -m 0700 "/dev/shm"; mount -t tmpfs    -o rw,nodev,nosuid,noexec,noatime,mode=1777,size=3% tmpfs    "/dev/shm"
install -d -o root -g root -m 0700 "/proc";    mount -t proc     -o rw,nodev,nosuid,noexec,noatime                   proc     "/proc"
install -d -o root -g root -m 0700 "/sys";     mount -t sysfs    -o rw,nodev,nosuid,noexec,noatime                   sysfs    "/sys"
install -d -o root -g root -m 0700 "/tmp";     mount -t tmpfs    -o rw,nodev,nosuid,noexec,noatime,mode=1777,size=7% tmpfs    "/tmp"
#############
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
for i in /lib/modules/$(uname -r)/*;do insmod $i;done
#############
rm -r /etc/hotplug.d
rm -r /etc/init.d
rm -r /etc/modules.d
rm -r /etc/rc.button
rm -r /etc/rc.d
rm -r /etc/sysctl.d
rm -r /lib/netifd
rm -r /lib/network
rm -r /lib/upgrade
rm -r /lib/wifi
rm -r /usr/bin/jsonfilter
rm -r /usr/lib/opkg
rm -r /usr/lib/libjson*
rm -r /usr/libexec
rm -r /usr/sbin/ntpd-hotplug
rm -r /var
#############
mount -o remount,ro,nosuid,noatime,size="$(df -P|awk '/^rootfs/{print$3}')k" /
#############

#############
syslogd -C300 -SD
klogd
#############
sysctl -p /etc/sysctl.conf
#############
ash /etc/nftables.rules
#############
ip link del bond0
#############
ip addr add 127.0.0.1/8 dev lo brd + scope host
ip route add 127.0.0.0/8 dev lo scope host
ip link set up lo
#############
ip link add wan type bond
brctl addbr lan
#############
ip link set up wan
ip link set up lan
#############

for i in /sys/class/net/*;do

 interface="$(basename ${i})"

 [ "${interface}" == "bonding_masters" ] && continue

 sysctl -w net.ipv4.conf.${interface}.rp_filter=1
 sysctl -w net.ipv4.conf.${interface}.drop_gratuitous_arp=1
 sysctl -w net.ipv6.conf.${interface}.autoconf=0
 sysctl -w net.ipv6.conf.${interface}.accept_ra=0

 [ "${interface:0:3}" == "eth" ] || [ "${interface:0:4}" == "wlan" ] && {

  install -o root -g root -m 0600 "/sys/class/net/${interface}/address" "/tmp/${interface}"

  until ip link set dev "${interface}" address "$(hexdump -n6 -ve '1/1 "%02X:"' /dev/urandom|head -c17)";do sleep .1;done

  ip link set up "${interface}"

 }

done

#############

sysctl -w net.ipv6.conf.wan.autoconf=1
sysctl -w net.ipv6.conf.wan.accept_ra=2

ifenslave wan wlan0 wlan1

ip addr add 192.168.0.3/24 dev wan
ip route add default via 192.168.0.1 scope global dev wan metric 0

wpa_supplicant -sBi wlan0 -c /etc/wpa_supplicant.5g
wpa_supplicant -sBi wlan1 -c /etc/wpa_supplicant.2g;ip link set down wlan1

#############

ip addr add 192.168.1.1/24 dev lan
ip addr add fd00:192:168::1/64 dev lan
brctl addif lan eth0
brctl addif lan eth1

#############
install -o root -g root -m 0600 /dev/null /tmp/leases && udhcpd -S /etc/udhcpd.lan
############# 

