#!/usr/bin/sh
#############
. /etc/services/variables ddns
#############
[ -f "${service_storage}/config" ] || install -o 5353 -g 5353 -m 0600 "${service_system}/config" "${service_storage}/config"
#############
printf "%s\n" "search localdomain" > /etc/resolv.conf
printf "%s\n" "options edns0" >> /etc/resolv.conf # no-aaaa
printf "%s\n" "nameserver 127.0.0.1" >> /etc/resolv.conf
chown root:root /etc/resolv.conf ; chmod 0664 /etc/resolv.conf
#############
. /etc/services/permissions 5353 5353 0700 0600
#############
