#!/bin/sh
#############
. /etc/services/ddns/install
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /bin/ash -c "exec ddns -f ${service_storage}/config </dev/null &>/dev/null & exit" ddns ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice -10 -u "ddns"
#############
