#!/usr/bin/sh
#############
. /etc/services/ddns/install
#############
pgrep -x ddns &>/dev/null && exit
#############
sysctl -w net.ipv4.ip_unprivileged_port_start=0
su -l -s /usr/bin/sh -c "setsid ddns -f ${service_storage}/config </dev/null &>/dev/null & exit" ddns ; sleep 1
sysctl -w net.ipv4.ip_unprivileged_port_start=32768
#############
renice +5 -u "ddns"
#############
